version: "3"
services:
  worker:
    image: jil22400/dockercoins
  rng:
    image: asabella/rng
  hasher:
    image: alexisbonnet1997/hasher
  webui:
    image: brahimhamdi/webui:1.0
    ports:
      - "8000:80"
  redis:
    image: redis
