version: "3"
services:
  worker:
    image: brahimhamdi/worker:1.0
  rng:
    image: rng
    build: asabella/rng/
  hasher:
    image: brahimhamdi/hasher:1.0
  webui:
    image: brahimhamdi/webui:1.0
    ports:
      - "8000:80"
  redis:
    image: redis
